### ISSUE TITLE
Вложенность less

### ISSUE THREAD

**Issue by litvin0d** [Semyon919/123#1]
Пример как можно использовать вложенность в less, sass и прочих препроцессорах

Было:
```less
.footer {
  min-height: 254px;
  padding: 32px 24px 30px 24px;
  width: 100%;
  background-color: #ffffff;

  @media (min-width: @desktop-width) {
    min-height: 324px;
    padding: 59px 0 49px 0;
  }
}

.footer__box {
  margin: 0 auto;
  position: relative;

  &::before {
    content: "";
    position: absolute;
    width: calc(100% - 48px);
    height: 2px;
    background-color: #373334;
    left: 24px;
    top: 87px;
  }

  @media (min-width: @desktop-width) {
    width: 1504px;

    &::before {
      width: 100%;
      left: 0;
      top: 112px;
    }
  }
}

.footer__title {
  font-weight: 500;
  line-height: 22px;
  text-align: center;
  margin: 0 0 10px 0;

  @media (min-width: @desktop-width) {
    font-size: 24px;
    font-weight: 400;
    line-height: 28px;
    margin: 0 0 16px 0;
    text-align: left;
  }
}

.footer__list {
  margin: 0 auto 48px auto;
  padding: 0;
  list-style: none;
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  width: fit-content;

  @media (min-width: @desktop-width) {
    margin: 0 0 101px 0;
  }
}

.footer__item-link {
  display: block;

  &:hover {
    opacity: 0.6;
  }

  &:active {
    opacity: 0.3;
  }
}

.footer__line-box {
  @media (min-width: @desktop-width) {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }
}

.footer__text {
  font-size: 14px;
  line-height: 24px;
  text-align: center;
  margin: 0 0 20px 0;

  @media (min-width: @desktop-width) {
    width: 264px;
    text-align: left;
    margin: 0;
  }
}

.footer__logo-link {
  display: block;
  width: 69px;
  height: 20px;
  margin: 0 auto;

  &:hover {
    opacity: 0.7;
  }

  &:focus {
    outline: solid 2px #373334;
  }

  &:active {
    opacity: 0.4;
  }

  @media (min-width: @desktop-width) {
    margin: 0;
  }
}

```

Стало:
```less
.footer {
  min-height: 254px;
  padding: 32px 24px 30px 24px;
  width: 100%;
  background-color: #ffffff;

  @media (min-width: @desktop-width) {
    min-height: 324px;
    padding: 59px 0 49px 0;
  }

  &__box {
    margin: 0 auto;
    position: relative;

    &::before {
      content: "";
      position: absolute;
      width: calc(100% - 48px);
      height: 2px;
      background-color: #373334;
      left: 24px;
      top: 87px;
    }

    @media (min-width: @desktop-width) {
      width: 1504px;

      &::before {
        width: 100%;
        left: 0;
        top: 112px;
      }
    }
  }

  &__title {
    font-weight: 500;
    line-height: 22px;
    text-align: center;
    margin: 0 0 10px 0;

    @media (min-width: @desktop-width) {
      font-size: 24px;
      font-weight: 400;
      line-height: 28px;
      margin: 0 0 16px 0;
      text-align: left;
    }
  }

  &__list {
    margin: 0 auto 48px auto;
    padding: 0;
    list-style: none;
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    width: fit-content;

    @media (min-width: @desktop-width) {
      margin: 0 0 101px 0;
    }
  }

  &__item-link {
    &:hover {
      opacity: 0.6;
    }

    &:active {
      opacity: 0.3;
    }
  }

  &__line-box {
    @media (min-width: @desktop-width) {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
    }
  }

  &__text {
    font-size: 14px;
    line-height: 24px;
    text-align: center;
    margin: 0 0 20px 0;

    @media (min-width: @desktop-width) {
      width: 264px;
      text-align: left;
      margin: 0;
    }
  }

  &__logo-link {
    display: block;
    width: 69px;
    height: 20px;
    margin: 0 auto;

    &:hover {
      opacity: 0.7;
    }

    &:focus {
      outline: solid 2px #373334;
    }

    &:active {
      opacity: 0.4;
    }

    @media (min-width: @desktop-width) {
      margin: 0;
    }
  }
}

```
